### ISSUE TITLE
Svg files not loading in Chrome/Safari when "preview"ed

### ISSUE THREAD

**Issue by ustamansangat** [sbt/sbt-site#144]
https://github.com/sbt/sbt-site/blob/dee21a1dae72a13fb2840147595649c4a97dbbcd/src/main/scala/com/typesafe/sbt/site/preview.scala#L53-L63.

The above doesn't set a Content-Type response header, the browser displays it as a broken image.

**Comment by ennru** [comment]
Was that with Jekyll? Then this is fixed with #138, could you check, please.

**Comment by matthiasS-da** [comment]
I upgraded to version 1.4.0 and retried. I still don't see svg pictures in Chrome/Safari. In Firefox I could see them.

The developer console of Chrome reports Server Errors (code 500) when loading the picture (or when loading fonts, js scripts, ...) I can however directly load the picture from Chrome.
